### ISSUE TITLE
Curl Package conflict

### ISSUE THREAD

**Issue by alexbaciu** [3fs/puppet-phantomjs#12]
Hello,

I am trying to use this package but I have this error:

 Duplicate declaration: Package[curl] is already declared in file /tmp/vagrant-puppet/manifests-a11d1078b1b1f2e3bdea27312f6ba513/default.pp at line 118 at /etc/puppet/modules/phantomjs/manifests/init.pp:16 on node precise32

I have these installed:

package { [
    'build-essential',
    'selinux',
    'phpmyadmin',
    'vim',
    'curl',
    'bzip2',
    'libfontconfig1',
    'git-core',
    'mc',
    'openjdk-7-jre-headless',
    'libmysqlclient-dev',
    
  ]:
  ensure  => 'installed',
}

Any Idea?
Thank you

**Comment by igoraj** [comment]
You see this issue because module also tries to install curl package. Although we use `ensure_packages` to avoid situations like this, it fails because your code didn't use it, so I would recommend that you also use `ensure_packages` when declaring packages.

See here for more:
https://github.com/puppetlabs/puppetlabs-stdlib#ensure_packages
